services:
  api:
    env_file:
      - .env.prod
    environment:
      - NODE_ENV=production
    command: 'npm run production'
  socket:
    env_file:
      - .env.prod
    environment:
      - NODE_ENV=production
    command: 'npm run production'
